[server]
headless = true

[browser]
gatherUsageStats = false

[theme]
font = "sans-serif"
baseRadius = "medium"
showSidebarBorder = true

[theme.light]
primaryColor = "#2a78d6"
backgroundColor = "#fcfcfb"
secondaryBackgroundColor = "#f1f0ec"
textColor = "#0b0b0b"
borderColor = "#e6e5e1"
chartCategoricalColors = ["#2a78d6", "#eb6834", "#1baf7a", "#eda100", "#e87ba4", "#008300", "#4a3aa7", "#e34948"]
chartSequentialColors = ["#cde2fb", "#b7d3f6", "#9ec5f4", "#86b6ef", "#6da7ec", "#5598e7", "#3987e5", "#256abf", "#184f95", "#0d366b"]

[theme.dark]
primaryColor = "#3987e5"
backgroundColor = "#1a1a19"
secondaryBackgroundColor = "#262624"
textColor = "#f5f5f2"
borderColor = "#383835"
chartCategoricalColors = ["#3987e5", "#d95926", "#199e70", "#c98500", "#d55181", "#008300", "#9085e9", "#e66767"]
chartSequentialColors = ["#104281", "#184f95", "#1c5cab", "#256abf", "#2a78d6", "#3987e5", "#5598e7", "#6da7ec", "#86b6ef", "#b7d3f6"]
